In [1]:
import ee, os, re
import geemap
from datetime import datetime
import numpy as np
import rasterio #for reading images
import matplotlib.pyplot as plt 
import pandas as pd
import napari
from matplotlib import path

In [2]:
 def cloudscore(image):
        '''
        Inner function for computing cloud score such that we can remove 
        bad images from the landsat collections we download.
        Implementation in javascript can be found of Google Earth Engine 
        website under (landsat algorithms), translation to python by KH.
        Further help from Nicholas Clinton at 
        https://urldefense.com/v3/__https://gis.stackexchange.com/questions/252685/filter-landsat-images-base-on-cloud-cover-over-a-region-of-interest*5Cn__;JQ!!LLK065n_VXAQ!zP9K-68-_oPkaNWFZdbTYYnai85ggL4j3FhdqssLkim-RneBr2NqD6Ka4fu6yw-v$         '''
        cloud = ee.Algorithms.Landsat.simpleCloudScore(image).select('cloud')
        cloudiness = cloud.reduceRegion(ee.Reducer.mean(),
                                        geometry=region,
                                        scale=30)
        image = image.set(cloudiness)
        return image

In [3]:
# Trigger the authentication flow
ee.Authenticate()

# Initialize the library
ee.Initialize()

KeyboardInterrupt: Interrupted by user

In [2]:
def band_select(bands):
    
    bbox =[(79.8096398872554,42.295437794411406),
(79.8096398872554,42.169352359125746),
(80.24634643022415,42.169352359125746),
(80.24634643022415,42.295437794411406)]

    start_date = datetime(1999,1,1)
    end_date = datetime(2003,1,1)

    region = ee.Geometry.Polygon(bbox)

    collection = ee.ImageCollection('LANDSAT/LE07/C01/T1_TOA').filterDate(start_date,end_date).filterBounds(region)
    
    collection = collection.select(bands)
    collection_list = collection.toList(collection.size())

    # type(collection_list)
    collection_size = collection_list.size().getInfo()
    dates = geemap.image_dates(collection, date_format='YYYY-MM-dd').getInfo()
    glacier_name = "Engilchek"

#     list_a = []
    for i, date in enumerate(dates):
        subdir = "ee_data"
        image = ee.Image(collection_list.get(i))
        geemap.ee_export_image(image, filename = os.path.join("ee_data", "{}_{}.tif".format(glacier_name,date)), scale = 100, region = region, file_per_band = False)
    #     list_a.append(filename)
    image_names = []
    for i, date in enumerate(dates):
        image_names.append(os.path.join("ee_data", "{}_{}.tif".format(glacier_name,date)))
    return dates, region, bbox, image_names


In [14]:
dates, region, bbox, image_names = band_select(['B1','B2','B3'])

Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-07-09.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-07-25.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-08-10.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-08-26.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-10-13.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-11-30.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-12-16.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2000-01-17.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2000-02-18.tif
Generating URL ...
Please wa

Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-01-22.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-02-23.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-07-01.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-07-17.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-08-18.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-10-05.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-12-08.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-06-30.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-07-16.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github

Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-03-02.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-04-03.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-05-05.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-06-22.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-07-24.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-08-25.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-10-28.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-11-13.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-06-30.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github

Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2001-11-26.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2001-12-12.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2001-12-28.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-01-29.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-04-03.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-05-05.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-06-22.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-07-24.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-08-25.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github

In [3]:
with rasterio.open('ee_data//Engilchek_2001-10-02.tif') as src:
    first_band = src.read(1)
    img = src.read()

In [4]:
img.shape

(3, 145, 363)

In [4]:
viewer = napari.view_image(img)
napari.run()

In [9]:
ts = {str.lower(layer.name):layer.data for layer in viewer.layers}
ts.keys()

dict_keys(['img', 'ice', 'ice [1]', 'not_ice'])

In [17]:
import re
re.match("^ice.*", "ice [0]")

<re.Match object; span=(0, 7), match='ice [0]'>

In [18]:
ice_layers = {str.lower(layer.name):layer.data for layer in viewer.layers if re.match("^ice.*", str.lower(layer.name))}

In [35]:
non_ice_layers= {str.lower(layer.name):layer.data for layer in viewer.layers if re.match("^not_ice.*", str.lower(layer.name))}
non_ice_layers

{'not_ice': [array([[  0.        , 111.76998161,  43.39173962],
         [  0.        ,  98.5944238 ,  59.64159426],
         [  0.        ,  92.00664489,  77.64818994],
         [  0.        ,  90.68908911,  97.85071192],
         [  0.        ,  83.66212494,  95.65478562],
         [  0.        ,  80.14864286,  84.6751541 ],
         [  0.        ,  84.54049546,  60.08077952],
         [  0.        ,  84.97968072,  50.41870379],
         [  0.        ,  95.52012698,  44.7092954 ],
         [  0.        , 103.42546166,  36.80396072],
         [  0.        , 110.45242583,  42.5133691 ]])]}

In [66]:
for i, (x,y) in enumerate(non_ice_layers.items()):
    coordinates = np.delete(y[0],(0),axis=1)

In [67]:
coordinates

array([[111.76998161,  43.39173962],
       [ 98.5944238 ,  59.64159426],
       [ 92.00664489,  77.64818994],
       [ 90.68908911,  97.85071192],
       [ 83.66212494,  95.65478562],
       [ 80.14864286,  84.6751541 ],
       [ 84.54049546,  60.08077952],
       [ 84.97968072,  50.41870379],
       [ 95.52012698,  44.7092954 ],
       [103.42546166,  36.80396072],
       [110.45242583,  42.5133691 ]])

In [59]:
test = np.delete(b[0],(0),axis=1)
test

array([[111.76998161,  43.39173962],
       [ 98.5944238 ,  59.64159426],
       [ 92.00664489,  77.64818994],
       [ 90.68908911,  97.85071192],
       [ 83.66212494,  95.65478562],
       [ 80.14864286,  84.6751541 ],
       [ 84.54049546,  60.08077952],
       [ 84.97968072,  50.41870379],
       [ 95.52012698,  44.7092954 ],
       [103.42546166,  36.80396072],
       [110.45242583,  42.5133691 ]])

In [65]:
mask = containsWithin(test, img)
mask

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [9]:
viewer.add_shapes(test, shape_type="polygon", edge_color='red', face_color="blue")

<Shapes layer 'test' at 0x23edce8e940>

In [60]:
glacier = path.Path(test)

In [61]:
glacier.contains_points(np.array([[26,200]]))

array([False])

In [14]:
indices = np.where(np.all(img == img, axis=0))
pixels = np.array(list(zip(indices[0],indices[1])))

In [17]:
pixels

array([[  0,   0],
       [  0,   1],
       [  0,   2],
       ...,
       [144, 360],
       [144, 361],
       [144, 362]], dtype=int64)

In [99]:
glacier.contains_points(pixels).shape

(52635,)

In [32]:
viewer.layers[1]

<Shapes layer 'Shapes' at 0x23edcdb2e80>

In [63]:
# label_data = {str.lower(layer.name):layer.data for layer in viewer.layers}
# path_dimention = np.delete(ts["shapes"][0], (0), axis=1)

def containsWithin(path_dimention, img):
    glacier = path.Path(path_dimention)
    indices = np.where(np.all(img == img, axis=0))
    pixels = np.array(list(zip(indices[0],indices[1])))
#     return pixels
    return glacier.contains_points(pixels).reshape(img.shape[1:])

    

In [20]:
mask = containsWithin(path_dimention, img)

In [22]:
viewer.add_points(list(zip(np.where(mask == True)[0],np.where(mask == True)[1]))[100])

<Points layer 'Points' at 0x23edcde0ee0>

### CODIFIED

In [4]:
def run_napari(img):

    viewer = napari.view_image(img)
    napari.run()
    return viewer

def get_mask(fileName):

    with rasterio.open('ee_data//Engilchek_2001-10-02.tif') as src:
        img = src.read() 
    napariConcurrent = mlt.Process(target=run_napari, args=img)
    viewer = napariConcurrent.get()
    input("Press ENTER after annotation")
    while True:
        try:
            path_dimention = get_polygon_paths(viewer)
            mask = containsWithin(path_dimention, img)
        except KeyError:
            print("Annotate on UI")
            time.sleep(5)
        break
    return mask
    

def get_polygon_paths(viewer)-> list:

    ice_layers = {str.lower(layer.name):layer.data for layer in viewer.layers if re.match("^ice.*", str.lower(layer.name))}
    non_ice_layers= {str.lower(layer.name):layer.data for layer in viewer.layers if re.match("^no[nt]_ice.*", str.lower(layer.name))}
    ice_coordinate_list, non_ice_coordinate_list = list(),list()

    for i, (x,y) in enumerate(ice_layers.items()):
        ice_coordinate_list.append(np.delete(y[0],(0),axis=1))
    for i, (x,y) in enumerate(non_ice_layers.items()):
        non_ice_coordinate_list.append(np.delete(y[0],(0),axis=1))

    path_results = {"ice":ice_coordinate_list, "non_ice":non_ice_coordinate_list}
    return path_results

    
def containsWithin(path_dimention, img):

    glacier = path.Path(path_dimention)
    indices = np.where(np.all(img == img, axis=0))
    pixels = np.array(list(zip(indices[0],indices[1])))
#     return pixels
    return glacier.contains_points(pixels).reshape(img.shape[1:])

In [318]:
test_viewer = run_napari(img)

In [321]:
paths = get_polygon_paths(test_viewer)

In [324]:
def getPixelMask(viewer,img,paths):
    iceMask = np.logical_or.reduce([containsWithin(path,img) for path in paths["ice"]])
    nonIceMask = np.logical_or.reduce([containsWithin(path,img) for path in paths["non_ice"]])
    return iceMask, nonIceMask
a,b=getPixelMask(test_viewer,img,paths)

In [328]:
b 

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [137]:
test_result = list()
for path in get_polygon_paths(viewer)["ice"]:
    test_result.append(path)
#     test_result.append(containsWithin(paths, img))

In [193]:
paths = get_polygon_paths(test_viewer)
containMap = [containsWithin(path,img) for path in paths["ice"]]
[np.count_nonzero(cmap) for cmap in containMap]

[1106, 579, 311]

In [194]:
np.count_nonzero(np.logical_or.reduce(containMap))

1996

In [202]:
np.logical_or.reduce([containsWithin(path,img) for path in paths["non_ice"]]).shape

(145, 363)

In [170]:
path in paths["ice"]:
    containsWithin()

C:\Users\marke\AppData\Local\Temp/ipykernel_17476/80534844.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  path in paths["ice"]


False

In [192]:
np.count_nonzero(np.logical_or(containMap[0],containMap[1]))

1685

In [277]:
iceMask = np.logical_or.reduce([containsWithin(path,img) for path in paths["ice"]])
nonIceMask = np.logical_or.reduce([containsWithin(path,img) for path in paths["non_ice"]])

In [334]:
iceMask.shape

(145, 363)

In [251]:
np.count_nonzero(iceMask)

1996

In [337]:
list(zip(np.where(iceMask)[0],np.where(iceMask)[1]))

[(55, 179),
 (55, 180),
 (55, 181),
 (55, 182),
 (55, 183),
 (55, 184),
 (55, 185),
 (55, 186),
 (55, 187),
 (55, 188),
 (55, 189),
 (55, 190),
 (55, 191),
 (55, 192),
 (55, 193),
 (55, 194),
 (55, 195),
 (55, 196),
 (56, 168),
 (56, 169),
 (56, 170),
 (56, 171),
 (56, 172),
 (56, 173),
 (56, 174),
 (56, 175),
 (56, 176),
 (56, 177),
 (56, 178),
 (56, 179),
 (56, 180),
 (56, 181),
 (56, 182),
 (56, 183),
 (56, 184),
 (56, 185),
 (56, 186),
 (56, 187),
 (56, 188),
 (56, 189),
 (56, 190),
 (56, 191),
 (56, 192),
 (56, 193),
 (56, 194),
 (56, 195),
 (56, 196),
 (56, 197),
 (56, 198),
 (56, 199),
 (56, 200),
 (56, 211),
 (56, 212),
 (56, 213),
 (56, 214),
 (56, 215),
 (56, 216),
 (56, 217),
 (56, 218),
 (56, 219),
 (56, 220),
 (56, 221),
 (56, 222),
 (56, 223),
 (57, 164),
 (57, 165),
 (57, 166),
 (57, 167),
 (57, 168),
 (57, 169),
 (57, 170),
 (57, 171),
 (57, 172),
 (57, 173),
 (57, 174),
 (57, 175),
 (57, 176),
 (57, 177),
 (57, 178),
 (57, 179),
 (57, 180),
 (57, 181),
 (57, 182),
 (57

In [341]:
np.rollaxis(img,0,3)[55,179,:]

array([0.42638168, 0.41369256, 0.42470253], dtype=float32)

In [358]:
iceData=list()
for (x,y) in list(zip(np.where(iceMask)[0],np.where(iceMask)[1])):
    iceData.append(np.rollaxis(img,0,3)[x,y,:])

In [355]:
iceData.append(iceData)

In [357]:
iceData.shape

AttributeError: 'list' object has no attribute 'shape'

In [351]:
ice_label = np.array(["ice"]*np.array(iceData).shape[0])

In [352]:
ice_label

array(['ice', 'ice', 'ice', ..., 'ice', 'ice', 'ice'], dtype='<U3')

In [298]:
tas = np.rollaxis(img,0,3)
mask = np.repeat(iceMask[:,:,np.newaxis],3,axis=2)

In [ ]:
ma.array(np.arange(1,3),mask=np.array([0,0,1]))

In [310]:
img.shape

(3, 145, 363)

In [316]:
iceMask

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [258]:
np.rollaxis(img, 0,3).shape

(145, 363, 3)

In [228]:
ma.array(img, mask=iceMask)

MaskError: Mask and data not compatible: data size is 157905, mask size is 52635.

In [207]:
np.rollaxis(img, 0,3).shape

(145, 363, 3)

In [130]:
test = {str.lower(layer.name):layer.data for layer in viewer.layers if re.match("^ice.*", str.lower(layer.name))}
test

{'ice': [array([[ 0.        , 69.16901135, 64.47263212],
         [ 0.        , 69.16901135, 65.5705953 ],
         [ 0.        , 70.26697452, 65.5705953 ],
         [ 0.        , 70.26697452, 64.47263212]]),
  array([[ 0.        , 66.09471453, 90.82374775],
         [ 0.        , 66.09471453, 91.92171092],
         [ 0.        , 67.1926777 , 91.92171092],
         [ 0.        , 67.1926777 , 90.82374775]]),
  array([[ 0.        , 66.97308505, 70.18204051],
         [ 0.        , 66.97308505, 71.28000368],
         [ 0.        , 68.07104822, 71.28000368],
         [ 0.        , 68.07104822, 70.18204051]]),
  array([[  0.        ,  72.24330817,  64.03344686],
         [  0.        ,  66.09471453,  84.6751541 ],
         [  0.        ,  63.89878822, 123.76264228],
         [  0.        ,  59.50693562, 145.28272005],
         [  0.        ,  74.00004921, 146.60027583],
         [  0.        ,  77.07434604, 120.68834546],
         [  0.        ,  78.83108708, 102.24256452],
         [  0.  

In [135]:
viewer.layers[1].name

'ICE'

In [136]:
viewer.layers[1].data

[array([[ 0.        , 69.16901135, 64.47263212],
        [ 0.        , 69.16901135, 65.5705953 ],
        [ 0.        , 70.26697452, 65.5705953 ],
        [ 0.        , 70.26697452, 64.47263212]]),
 array([[ 0.        , 66.09471453, 90.82374775],
        [ 0.        , 66.09471453, 91.92171092],
        [ 0.        , 67.1926777 , 91.92171092],
        [ 0.        , 67.1926777 , 90.82374775]]),
 array([[ 0.        , 66.97308505, 70.18204051],
        [ 0.        , 66.97308505, 71.28000368],
        [ 0.        , 68.07104822, 71.28000368],
        [ 0.        , 68.07104822, 70.18204051]]),
 array([[  0.        ,  72.24330817,  64.03344686],
        [  0.        ,  66.09471453,  84.6751541 ],
        [  0.        ,  63.89878822, 123.76264228],
        [  0.        ,  59.50693562, 145.28272005],
        [  0.        ,  74.00004921, 146.60027583],
        [  0.        ,  77.07434604, 120.68834546],
        [  0.        ,  78.83108708, 102.24256452],
        [  0.        ,  80.58782812,  71.4

# Final Test

In [483]:
!pwd

'pwd' is not recognized as an internal or external command,
operable program or batch file.


In [21]:
# def runNapari(img):

#     viewer = napari.view_image(img)
#     napari.run()
#     return viewer


# def getPolygonMasks(viewer)-> list:

#     ice_layers = {str.lower(layer.name):layer.data for layer in viewer.layers if re.match("^ice.*", str.lower(layer.name))}
#     non_ice_layers= {str.lower(layer.name):layer.data for layer in viewer.layers if re.match("^not.*ice.*", str.lower(layer.name))}
#     ice_coordinate_list, non_ice_coordinate_list = list(),list()

#     for i, (x,y) in enumerate(ice_layers.items()):
#         ice_coordinate_list.append(np.delete(y[0],(0),axis=1))
#     for i, (x,y) in enumerate(non_ice_layers.items()):
#         non_ice_coordinate_list.append(np.delete(y[0],(0),axis=1))

#     path_results = {"ice":ice_coordinate_list, "non_ice":non_ice_coordinate_list}
#     return path_results

    
# def containsWithin(path_dimention, img):

#     glacier = path.Path(path_dimention)
#     indices = np.where(np.all(img == img, axis=0))
#     pixels = np.array(list(zip(indices[0],indices[1])))
# #     return pixels
#     return glacier.contains_points(pixels).reshape(img.shape[1:])


# def getPixelMask(img,paths):

#     iceMask = np.where(np.logical_or.reduce([containsWithin(path,img) for path in paths["ice"]]))
#     nonIceMask = np.where(np.logical_or.reduce([containsWithin(path,img) for path in paths["non_ice"]]))

#     ice_coordinates = list(zip(iceMask[0],iceMask[1]))
#     non_ice_coordinates = list(zip(nonIceMask[0],nonIceMask[1]))    
#     iceData,nonIceData=list(),list()
#     for (x,y) in ice_coordinates:
#         iceData.append(np.rollaxis(img,0,3)[x,y,:])
#     for (x,y) in non_ice_coordinates:
#         nonIceData.append(np.rollaxis(img,0,3)[x,y,:])
#     return np.array(iceData), np.array(nonIceData)


# def testPixelMask(img,paths,viewer):

#     iceMask = np.where(np.logical_or.reduce([containsWithin(path,img) for path in paths["ice"]]))
#     nonIceMask = np.where(np.logical_or.reduce([containsWithin(path,img) for path in paths["non_ice"]]))

#     ice_coordinates = list(zip(iceMask[0],iceMask[1]))
#     non_ice_coordinates = list(zip(nonIceMask[0],nonIceMask[1]))    

#     viewer.add_points(ice_coordinates,face_color="red",edge_color ="red",size=1)
#     viewer.add_points(non_ice_coordinates,face_color="blue",edge_color ="blue",size=1)
    
#     return ice_coordinates,non_ice_coordinates

# def test_getPixelMask(img,paths):
#     iceMask = np.where(np.logical_or.reduce([containsWithin(path,img) for path in paths["ice"]]))
#     nonIceMask = np.where(np.logical_or.reduce([containsWithin(path,img) for path in paths["non_ice"]]))

#     ice_coordinates = list(zip(iceMask[0],iceMask[1]))
#     non_ice_coordinates = list(zip(nonIceMask[0],nonIceMask[1]))


#     c,d = ice_coordinates,non_ice_coordinates
#     return c,d

#     a,b = ice_coordinates,non_ice_coordinates
#     return a,b
#     print(iceMask.shape, nonIceMask.shape)
    
#     iceData,nonIceData=list(),list()
#     for (x,y) in ice_coordinates:
#         iceData.append(np.rollaxis(img,0,3)[x,y,:])
#     for (x,y) in non_ice_coordinates:
#         nonIceData.append(np.rollaxis(img,0,3)[x,y,:])
#     return np.array(iceData), np.array(nonIceData)

In [101]:

def runNapari(img_path):
    with rasterio.open(img_path) as src:
        img = src.read()
   
    viewer = napari.view_image(img)
    return viewer, img


def getPolygonMasks(viewer)-> list:
    ice_layers = {str.lower(layer.name):layer.data for layer in viewer.layers if re.match("^ice.*", str.lower(layer.name))}
    non_ice_layers= {str.lower(layer.name):layer.data for layer in viewer.layers if re.match("^not.*ice.*", str.lower(layer.name))}
    ice_coordinate_list, non_ice_coordinate_list = list(),list()

    for i, (x,y) in enumerate(ice_layers.items()):
        ice_coordinate_list.append(np.delete(y[0],(0),axis=1))
    for i, (x,y) in enumerate(non_ice_layers.items()):
        non_ice_coordinate_list.append(np.delete(y[0],(0),axis=1))

    path_results = {"ice":ice_coordinate_list, "non_ice":non_ice_coordinate_list}
    return path_results

    
def containsWithin(path_dimention, img):
    glacier = path.Path(path_dimention)
    indices = np.where(np.all(img == img, axis=0))
    pixels = np.array(list(zip(indices[0],indices[1])))
#     return pixels
    return glacier.contains_points(pixels).reshape(img.shape[1:])


def getPixelMask(img,paths):
    iceMask = np.where(np.logical_or.reduce([containsWithin(path,img) for path in paths["ice"]]))
    nonIceMask = np.where(np.logical_or.reduce([containsWithin(path,img) for path in paths["non_ice"]]))

    ice_coordinates = list(zip(iceMask[0],iceMask[1]))
    non_ice_coordinates = list(zip(nonIceMask[0],nonIceMask[1]))    
    iceData,nonIceData=list(),list()
    for (x,y) in ice_coordinates:
        iceData.append(np.rollaxis(img,0,3)[x,y,:])
    for (x,y) in non_ice_coordinates:
        nonIceData.append(np.rollaxis(img,0,3)[x,y,:])
    return np.array(iceData), np.array(nonIceData)


def getPixelMask(img,paths):
    iceMask = np.where(np.logical_or.reduce([containsWithin(path,img) for path in paths["ice"]]))
    nonIceMask = np.where(np.logical_or.reduce([containsWithin(path,img) for path in paths["non_ice"]]))

    ice_coordinates = list(zip(iceMask[0],iceMask[1]))
    non_ice_coordinates = list(zip(nonIceMask[0],nonIceMask[1]))    
    iceData,nonIceData=list(),list()
    for (x,y) in ice_coordinates:
        iceData.append(np.rollaxis(img,0,3)[x,y,:])
    for (x,y) in non_ice_coordinates:
        nonIceData.append(np.rollaxis(img,0,3)[x,y,:])
    return np.array(iceData), np.array(nonIceData)


def getTrainingData(iceData, nonIceData):
    data,labels = np.array([]), np.array([])

    iceLabels = np.array(["Ice"]*iceData.shape[0])
    nonIceLabels = np.array(["Not Ice"]*nonIceData.shape[0])
    data = np.vstack((iceData, nonIceData))
    labels = np.hstack((iceLabels, nonIceLabels))
    return data, labels


def createLog(directory):
    logpath = os.path.join(directory, "imgAnnotatedData.pickle")
    try:
        imageList = pickle.load(open(logpath,"rb"))
    except (OSError, IOError) as e:
        imageList = []
        pickle.dump(imageList, open(logpath,"wb"))
    return imageList

def updateLog(imageList,directory):
    logpath = os.path.join(directory, "imgAnnotatedData.pickle")
    pickle.dump(imageList, open(logpath,"wb"))


In [102]:

# img = r"C:\Users\marke\Documents\DSC180A-Q1\ee_data\Engilchek_2000-03-21.tif"
# t_viewer,image = runNapari(img)

In [139]:
paths = getPolygonMasks(t_viewer)
ice,not_ice = getPixelMask(image,paths)

In [104]:
np.vstack((ice,not_ice)).shape

(2598, 3)

In [141]:
a,b = getTrainingData(ice,not_ice)
print(a.shape, b.shape)

(2598, 3) (2598,)


In [146]:
np.vstack((a,a)).shape
np.hstack((b,b)).shape

(5196,)

In [138]:
dfTest = pd.DataFrame(a)
dfTest.assign(label=pd.Series(b))

0         1         2    label
0     0.377139  0.373681  0.359383      Ice
1     0.425570  0.478785  0.453397      Ice
2     0.425570  0.478785  0.453397      Ice
3     0.242223  0.192668  0.173200      Ice
4     0.252601  0.200454  0.180574      Ice
...        ...       ...       ...      ...
2593  0.425570  0.478785  0.453397  Not Ice
2594  0.425570  0.478785  0.453397  Not Ice
2595  0.425570  0.478785  0.453397  Not Ice
2596  0.425570  0.478785  0.453397  Not Ice
2597  0.425570  0.478785  0.453397  Not Ice

[2598 rows x 4 columns]

In [126]:
a=np.arange(24).reshape((8,3))
a
# iterables=[[1,2,3],[1,2]['m1','m2'],['A','B']]
# index = pd.MultiIndex.from_product(iterables, names=['time','sub','meas','cond'])
pd.DataFrame(a,columns=[1,2,3])


1   2   3
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14
5  15  16  17
6  18  19  20
7  21  22  23

In [107]:
pd.DataFrame({"Data":a, "Label":b})

ValueError: Data must be 1-dimensional

In [47]:
iceLabels = np.array(["Ice"]*test[1].shape[0])
lables = np.hstack((iceLabels, iceLabels))
print(test[1].shape, iceLabels.shape, lables.shape)

(742, 3) (742,) (1484,)


In [38]:
np.vstack(test)

array([[0.42038128, 0.45153606, 0.4533969 ],
       [0.42557037, 0.47878534, 0.4533969 ],
       [0.42557037, 0.47878534, 0.4533969 ],
       ...,
       [0.35119358, 0.33475348, 0.35200983],
       [0.37713897, 0.3678419 , 0.38334763],
       [0.41346252, 0.42234042, 0.43311948]], dtype=float32)

In [29]:
paths

{'ice': [], 'non_ice': []}

In [35]:
a

[(65, 142),
 (65, 143),
 (65, 144),
 (65, 145),
 (65, 146),
 (65, 147),
 (65, 148),
 (65, 149),
 (65, 150),
 (66, 98),
 (66, 99),
 (66, 100),
 (66, 101),
 (66, 102),
 (66, 103),
 (66, 104),
 (66, 105),
 (66, 106),
 (66, 107),
 (66, 108),
 (66, 109),
 (66, 110),
 (66, 111),
 (66, 112),
 (66, 113),
 (66, 114),
 (66, 115),
 (66, 116),
 (66, 117),
 (66, 118),
 (66, 119),
 (66, 120),
 (66, 130),
 (66, 131),
 (66, 132),
 (66, 133),
 (66, 134),
 (66, 135),
 (66, 136),
 (66, 137),
 (66, 138),
 (66, 139),
 (66, 140),
 (66, 141),
 (66, 142),
 (66, 143),
 (66, 144),
 (66, 145),
 (66, 146),
 (66, 147),
 (66, 148),
 (66, 149),
 (66, 150),
 (67, 81),
 (67, 82),
 (67, 83),
 (67, 84),
 (67, 85),
 (67, 86),
 (67, 87),
 (67, 88),
 (67, 89),
 (67, 90),
 (67, 91),
 (67, 92),
 (67, 93),
 (67, 94),
 (67, 95),
 (67, 96),
 (67, 97),
 (67, 98),
 (67, 99),
 (67, 100),
 (67, 101),
 (67, 102),
 (67, 103),
 (67, 104),
 (67, 105),
 (67, 106),
 (67, 107),
 (67, 108),
 (67, 109),
 (67, 110),
 (67, 111),
 (67, 112),
 

In [28]:
t_viewer.add_points(testpoints[1],face_color="blue",edge_color ="blue",size=1)

<Points layer 'Points [1]' at 0x22803a07400>

In [453]:
list(zip(np.where(iceMask)[0],np.where(iceMask)[1]))

([(0, 0),
  (0, 1),
  (0, 2),
  (0, 3),
  (0, 4),
  (0, 5),
  (0, 6),
  (0, 7),
  (0, 8),
  (0, 9),
  (0, 10),
  (0, 11),
  (0, 12),
  (0, 13),
  (0, 14),
  (0, 15),
  (0, 16),
  (0, 17),
  (0, 18),
  (0, 19),
  (0, 20),
  (0, 21),
  (0, 22),
  (0, 23),
  (0, 24),
  (0, 25),
  (0, 26),
  (0, 27),
  (0, 28),
  (0, 29),
  (0, 30),
  (0, 31),
  (0, 32),
  (0, 33),
  (0, 34),
  (0, 35),
  (0, 36),
  (0, 37),
  (0, 38),
  (0, 39),
  (0, 40),
  (0, 41),
  (0, 42),
  (0, 43),
  (0, 44),
  (0, 45),
  (0, 46),
  (0, 47),
  (0, 48),
  (0, 49),
  (0, 50),
  (0, 51),
  (0, 52),
  (0, 53),
  (0, 54),
  (0, 55),
  (0, 56),
  (0, 57),
  (0, 58),
  (0, 59),
  (0, 60),
  (0, 61),
  (0, 62),
  (0, 63),
  (0, 64),
  (0, 65),
  (0, 66),
  (0, 67),
  (0, 68),
  (0, 69),
  (0, 70),
  (0, 71),
  (0, 72),
  (0, 73),
  (0, 74),
  (0, 75),
  (0, 76),
  (0, 77),
  (0, 78),
  (0, 79),
  (0, 80),
  (0, 81),
  (0, 82),
  (0, 83),
  (0, 84),
  (0, 85),
  (0, 86),
  (0, 87),
  (0, 88),
  (0, 89),
  (0, 90),
  (0, 91)

In [451]:
print(pd.DataFrame(test[0][0]).describe(), f"\n {pd.DataFrame(test[0][1]).describe()}")

         0
count  2.0
mean   0.0
std    0.0
min    0.0
25%    0.0
50%    0.0
75%    0.0
max    0.0 
               0
count  2.000000
mean   0.500000
std    0.707107
min    0.000000
25%    0.250000
50%    0.500000
75%    0.750000
max    1.000000


In [452]:
print(pd.DataFrame(test[1][0]).describe(), f"\n {pd.DataFrame(test[1][1]).describe()}")

         0
count  2.0
mean   0.0
std    0.0
min    0.0
25%    0.0
50%    0.0
75%    0.0
max    0.0 
               0
count  2.000000
mean   0.500000
std    0.707107
min    0.000000
25%    0.250000
50%    0.500000
75%    0.750000
max    1.000000


In [421]:
a = np.where(np.logical_or.reduce([containsWithin(path,img) for path in paths["ice"]])) 
b = np.where(np.logical_or.reduce([containsWithin(path,img) for path in paths["non_ice"]]))

np.count_nonzero(a[0] != b[0])

0

In [422]:
paths["non_ice"]

[array([[ 65.03152467,  86.19228092],
        [ 66.76520143, 106.00572961],
        [ 62.05950737, 144.64195456],
        [ 62.05950737, 144.64195456],
        [ 71.22322739, 146.62329943],
        [ 71.22322739, 146.62329943],
        [ 79.64394308, 100.30936311],
        [ 80.1392793 ,  79.00990577],
        [ 72.46156793,  77.27622901],
        [ 65.52686089,  85.6969447 ]]),
 array([[ 60.6432737 , 153.15189296],
        [ 56.9417907 , 167.69343332],
        [ 55.75202831, 182.89595279],
        [ 62.89060266, 182.49936532],
        [ 67.25306477, 179.85544889],
        [ 67.25306477, 169.27978318],
        [ 67.25306477, 169.27978318],
        [ 68.0462397 , 154.07726371],
        [ 60.11449041, 153.01969714]])]