In [1]:
import ee, os
import geemap
from datetime import datetime
import numpy as np
import rasterio #for reading images
import matplotlib.pyplot as plt 
import pandas as pd
import napari
from matplotlib import path

In [2]:
 def cloudscore(image):
        '''
        Inner function for computing cloud score such that we can remove 
        bad images from the landsat collections we download.
        Implementation in javascript can be found of Google Earth Engine 
        website under (landsat algorithms), translation to python by KH.
        Further help from Nicholas Clinton at 
        https://urldefense.com/v3/__https://gis.stackexchange.com/questions/252685/filter-landsat-images-base-on-cloud-cover-over-a-region-of-interest*5Cn__;JQ!!LLK065n_VXAQ!zP9K-68-_oPkaNWFZdbTYYnai85ggL4j3FhdqssLkim-RneBr2NqD6Ka4fu6yw-v$         '''
        cloud = ee.Algorithms.Landsat.simpleCloudScore(image).select('cloud')
        cloudiness = cloud.reduceRegion(ee.Reducer.mean(),
                                        geometry=region,
                                        scale=30)
        image = image.set(cloudiness)
        return image

In [3]:
# Trigger the authentication flow
ee.Authenticate()

# Initialize the library
ee.Initialize()

KeyboardInterrupt: Interrupted by user

In [2]:
def band_select(bands):
    
    bbox =[(79.8096398872554,42.295437794411406),
(79.8096398872554,42.169352359125746),
(80.24634643022415,42.169352359125746),
(80.24634643022415,42.295437794411406)]

    start_date = datetime(1999,1,1)
    end_date = datetime(2003,1,1)

    region = ee.Geometry.Polygon(bbox)

    collection = ee.ImageCollection('LANDSAT/LE07/C01/T1_TOA').filterDate(start_date,end_date).filterBounds(region)
    
    collection = collection.select(bands)
    collection_list = collection.toList(collection.size())

    # type(collection_list)
    collection_size = collection_list.size().getInfo()
    dates = geemap.image_dates(collection, date_format='YYYY-MM-dd').getInfo()
    glacier_name = "Engilchek"

#     list_a = []
    for i, date in enumerate(dates):
        subdir = "ee_data"
        image = ee.Image(collection_list.get(i))
        geemap.ee_export_image(image, filename = os.path.join("ee_data", "{}_{}.tif".format(glacier_name,date)), scale = 100, region = region, file_per_band = False)
    #     list_a.append(filename)
    image_names = []
    for i, date in enumerate(dates):
        image_names.append(os.path.join("ee_data", "{}_{}.tif".format(glacier_name,date)))
    return dates, region, bbox, image_names


In [14]:
dates, region, bbox, image_names = band_select(['B1','B2','B3'])

Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-07-09.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-07-25.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-08-10.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-08-26.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-10-13.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-11-30.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-12-16.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2000-01-17.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2000-02-18.tif
Generating URL ...
Please wa

Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-01-22.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-02-23.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-07-01.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-07-17.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-08-18.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-10-05.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-12-08.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-06-30.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-07-16.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github

Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-03-02.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-04-03.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-05-05.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-06-22.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-07-24.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-08-25.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-10-28.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-11-13.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_1999-06-30.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github

Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2001-11-26.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2001-12-12.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2001-12-28.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-01-29.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-04-03.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-05-05.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-06-22.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-07-24.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github\DSC180A-Q1\ee_data\Engilchek_2002-08-25.tif
Generating URL ...
Please wait ...
Data downloaded to D:\github

In [3]:
with rasterio.open('ee_data//Engilchek_2001-10-02.tif') as src:
    first_band = src.read(1)
    img = src.read()

In [4]:
img.shape

(3, 145, 363)

In [4]:
viewer = napari.view_image(img)
napari.run()

In [9]:
ts = {str.lower(layer.name):layer.data for layer in viewer.layers}
ts.keys()

dict_keys(['img', 'ice', 'ice [1]', 'not_ice'])

In [17]:
import re
re.match("^ice.*", "ice [0]")

<re.Match object; span=(0, 7), match='ice [0]'>

In [18]:
ice_layers = {str.lower(layer.name):layer.data for layer in viewer.layers if re.match("^ice.*", str.lower(layer.name))}

In [35]:
non_ice_layers= {str.lower(layer.name):layer.data for layer in viewer.layers if re.match("^not_ice.*", str.lower(layer.name))}
non_ice_layers

{'not_ice': [array([[  0.        , 111.76998161,  43.39173962],
         [  0.        ,  98.5944238 ,  59.64159426],
         [  0.        ,  92.00664489,  77.64818994],
         [  0.        ,  90.68908911,  97.85071192],
         [  0.        ,  83.66212494,  95.65478562],
         [  0.        ,  80.14864286,  84.6751541 ],
         [  0.        ,  84.54049546,  60.08077952],
         [  0.        ,  84.97968072,  50.41870379],
         [  0.        ,  95.52012698,  44.7092954 ],
         [  0.        , 103.42546166,  36.80396072],
         [  0.        , 110.45242583,  42.5133691 ]])]}

In [66]:
for i, (x,y) in enumerate(non_ice_layers.items()):
    coordinates = np.delete(y[0],(0),axis=1)

In [67]:
coordinates

array([[111.76998161,  43.39173962],
       [ 98.5944238 ,  59.64159426],
       [ 92.00664489,  77.64818994],
       [ 90.68908911,  97.85071192],
       [ 83.66212494,  95.65478562],
       [ 80.14864286,  84.6751541 ],
       [ 84.54049546,  60.08077952],
       [ 84.97968072,  50.41870379],
       [ 95.52012698,  44.7092954 ],
       [103.42546166,  36.80396072],
       [110.45242583,  42.5133691 ]])

In [59]:
test = np.delete(b[0],(0),axis=1)
test

array([[111.76998161,  43.39173962],
       [ 98.5944238 ,  59.64159426],
       [ 92.00664489,  77.64818994],
       [ 90.68908911,  97.85071192],
       [ 83.66212494,  95.65478562],
       [ 80.14864286,  84.6751541 ],
       [ 84.54049546,  60.08077952],
       [ 84.97968072,  50.41870379],
       [ 95.52012698,  44.7092954 ],
       [103.42546166,  36.80396072],
       [110.45242583,  42.5133691 ]])

In [65]:
mask = containsWithin(test, img)
mask

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [9]:
viewer.add_shapes(test, shape_type="polygon", edge_color='red', face_color="blue")

<Shapes layer 'test' at 0x23edce8e940>

In [60]:
glacier = path.Path(test)

In [61]:
glacier.contains_points(np.array([[26,200]]))

array([False])

In [14]:
indices = np.where(np.all(img == img, axis=0))
pixels = np.array(list(zip(indices[0],indices[1])))

In [17]:
pixels

array([[  0,   0],
       [  0,   1],
       [  0,   2],
       ...,
       [144, 360],
       [144, 361],
       [144, 362]], dtype=int64)

In [99]:
glacier.contains_points(pixels).shape

(52635,)

In [32]:
viewer.layers[1]

<Shapes layer 'Shapes' at 0x23edcdb2e80>

In [63]:
# label_data = {str.lower(layer.name):layer.data for layer in viewer.layers}
# path_dimention = np.delete(ts["shapes"][0], (0), axis=1)

def containsWithin(path_dimention, img):
    glacier = path.Path(path_dimention)
    indices = np.where(np.all(img == img, axis=0))
    pixels = np.array(list(zip(indices[0],indices[1])))
#     return pixels
    return glacier.contains_points(pixels).reshape(img.shape[1:])

    

In [20]:
mask = containsWithin(path_dimention, img)

In [22]:
viewer.add_points(list(zip(np.where(mask == True)[0],np.where(mask == True)[1]))[100])

<Points layer 'Points' at 0x23edcde0ee0>

### CODIFIED

In [144]:
def run_napari(img):

    viewer = napari.view_image(img)
    napari.run()
    return viewer

def get_mask(fileName):

    with rasterio.open('ee_data//Engilchek_2001-10-02.tif') as src:
        img = src.read() 
    napariConcurrent = mlt.Process(target=run_napari, args=img)
    viewer = napariConcurrent.get()
    input("Press ENTER after annotation")
    while True:
        try:
            path_dimention = get_polygon_paths(viewer)
            mask = containsWithin(path_dimention, img)
        except KeyError:
            print("Annotate on UI")
            time.sleep(5)
        break
    return mask
    

def get_polygon_paths(viewer)-> list:

    ice_layers = {str.lower(layer.name):layer.data for layer in viewer.layers if re.match("^ice.*", str.lower(layer.name))}
    non_ice_layers= {str.lower(layer.name):layer.data for layer in viewer.layers if re.match("^not_ice.*", str.lower(layer.name))}
    ice_coordinate_list, non_ice_coordinate_list = list(),list()

    for i, (x,y) in enumerate(ice_layers.items()):
        ice_coordinate_list.append(np.delete(y[0],(0),axis=1))
    for i, (x,y) in enumerate(non_ice_layers.items()):
        non_ice_coordinate_list.append(np.delete(y[0],(0),axis=1))

    path_results = {"ice":ice_coordinate_list, "non_ice":non_ice_coordinate_list}
    return path_results

    
def containsWithin(path_dimention, img):

    glacier = path.Path(path_dimention)
    indices = np.where(np.all(img == img, axis=0))
    pixels = np.array(list(zip(indices[0],indices[1])))
#     return pixels
    return glacier.contains_points(pixels).reshape(img.shape[1:])

In [134]:
# test_viewer = run_napari(img)

In [137]:
test_result = list()
for path in get_polygon_paths(viewer)["ice"]:
    test_result.append(path)
#     test_result.append(containsWithin(paths, img))

In [145]:
 get_polygon_paths(viewer)

{'ice': [array([[69.16901135, 64.47263212],
         [69.16901135, 65.5705953 ],
         [70.26697452, 65.5705953 ],
         [70.26697452, 64.47263212]]),
  array([[ 59.06775036, 151.43131369],
         [ 57.31100932, 168.55953885],
         [ 54.67589775, 183.05265244],
         [ 54.67589775, 190.07961661],
         [ 57.31100932, 196.66739552],
         [ 66.97308505, 200.1808776 ],
         [ 66.09471453, 180.85672614],
         [ 68.72982609, 161.53257468],
         [ 70.04738187, 151.43131369],
         [ 60.8244914 , 152.30968421]])],
 'non_ice': [array([[111.76998161,  43.39173962],
         [ 98.5944238 ,  59.64159426],
         [ 92.00664489,  77.64818994],
         [ 90.68908911,  97.85071192],
         [ 83.66212494,  95.65478562],
         [ 80.14864286,  84.6751541 ],
         [ 84.54049546,  60.08077952],
         [ 84.97968072,  50.41870379],
         [ 95.52012698,  44.7092954 ],
         [103.42546166,  36.80396072],
         [110.45242583,  42.5133691 ]])]}

In [138]:
test_result

[array([[69.16901135, 64.47263212],
        [69.16901135, 65.5705953 ],
        [70.26697452, 65.5705953 ],
        [70.26697452, 64.47263212]]),
 array([[ 59.06775036, 151.43131369],
        [ 57.31100932, 168.55953885],
        [ 54.67589775, 183.05265244],
        [ 54.67589775, 190.07961661],
        [ 57.31100932, 196.66739552],
        [ 66.97308505, 200.1808776 ],
        [ 66.09471453, 180.85672614],
        [ 68.72982609, 161.53257468],
        [ 70.04738187, 151.43131369],
        [ 60.8244914 , 152.30968421]])]

In [118]:
te = np.logical_or(test_result[0],test_result[1])

In [125]:
np.count_nonzero(test_result[0])

1

In [130]:
test = {str.lower(layer.name):layer.data for layer in viewer.layers if re.match("^ice.*", str.lower(layer.name))}
test

{'ice': [array([[ 0.        , 69.16901135, 64.47263212],
         [ 0.        , 69.16901135, 65.5705953 ],
         [ 0.        , 70.26697452, 65.5705953 ],
         [ 0.        , 70.26697452, 64.47263212]]),
  array([[ 0.        , 66.09471453, 90.82374775],
         [ 0.        , 66.09471453, 91.92171092],
         [ 0.        , 67.1926777 , 91.92171092],
         [ 0.        , 67.1926777 , 90.82374775]]),
  array([[ 0.        , 66.97308505, 70.18204051],
         [ 0.        , 66.97308505, 71.28000368],
         [ 0.        , 68.07104822, 71.28000368],
         [ 0.        , 68.07104822, 70.18204051]]),
  array([[  0.        ,  72.24330817,  64.03344686],
         [  0.        ,  66.09471453,  84.6751541 ],
         [  0.        ,  63.89878822, 123.76264228],
         [  0.        ,  59.50693562, 145.28272005],
         [  0.        ,  74.00004921, 146.60027583],
         [  0.        ,  77.07434604, 120.68834546],
         [  0.        ,  78.83108708, 102.24256452],
         [  0.  

In [135]:
viewer.layers[1].name

'ICE'

In [136]:
viewer.layers[1].data

[array([[ 0.        , 69.16901135, 64.47263212],
        [ 0.        , 69.16901135, 65.5705953 ],
        [ 0.        , 70.26697452, 65.5705953 ],
        [ 0.        , 70.26697452, 64.47263212]]),
 array([[ 0.        , 66.09471453, 90.82374775],
        [ 0.        , 66.09471453, 91.92171092],
        [ 0.        , 67.1926777 , 91.92171092],
        [ 0.        , 67.1926777 , 90.82374775]]),
 array([[ 0.        , 66.97308505, 70.18204051],
        [ 0.        , 66.97308505, 71.28000368],
        [ 0.        , 68.07104822, 71.28000368],
        [ 0.        , 68.07104822, 70.18204051]]),
 array([[  0.        ,  72.24330817,  64.03344686],
        [  0.        ,  66.09471453,  84.6751541 ],
        [  0.        ,  63.89878822, 123.76264228],
        [  0.        ,  59.50693562, 145.28272005],
        [  0.        ,  74.00004921, 146.60027583],
        [  0.        ,  77.07434604, 120.68834546],
        [  0.        ,  78.83108708, 102.24256452],
        [  0.        ,  80.58782812,  71.4